-- Setup
CALL CORE.CREATE_EAI_OBJECTS();

-- Load data
CALL CORE.LOAD_PIPELINE_RUNS();
CALL CORE.LOAD_TASK_RUNS();
CALL CORE.LOAD_OPERATIONS();

-- Check data is present
SELECT * FROM PUBLIC.PIPELINE_RUNS;
SELECT * FROM PUBLIC.TASK_RUNS;
SELECT * FROM PUBLIC.OPERATIONS;

-- Debugging - low-level procedures to fetch raw data
CALL CORE.GET_PIPELINE_RUNS();
CALL CORE.GET_TASK_RUNS();
CALL CORE.GET_OPERATIONS();
